Change getDirectoryDeviceId to getDeviceSerialNumber due to cros66 change
salopensource/chromesal pull request #7
Opened 2020-10-16 20:12 UTC by msnorman343

2020-10-20 17:41 UTC, grahamgilbert commented
We should have `getDirectoryDeviceId` as a "fact" as well.

2020-10-20 20:29 UTC, msnorman343 commented
Great idea!  Let me take a look at this.

2020-10-21 18:28 UTC, grahamgilbert requested changes

2020-10-21 18:28 UTC, grahamgilbert commented on popup.js
> +      'device_id': data.google_device_identifier,
I don't see where this is put into the new Sal 4 format - am I missing it somewhere? https://github.com/salopensource/sal/wiki/Checkin-and-checkin-modules

2020-10-27 18:48 UTC, msnorman343 commented
Let me know if anything further is needed.

2020-11-17 16:16 UTC, grahamgilbert requested changes

2020-11-17 16:16 UTC, grahamgilbert commented on popup.js
> +    'Google_Device_ID': data.google_device_identifier
This should be lower case

2020-11-17 16:16 UTC, grahamgilbert commented on popup.js
> +    callbackCount++;
You’re increasing the callback count but not increasing the callback total

2020-11-18 00:45 UTC, grahamgilbert approved these changes

2020-11-18 00:45 UTC, merged